# Generated by Django 5.1.3 on 2025-01-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="location",
        ),
    ]
