# Generated by Django 5.1.3 on 2025-01-13 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('operation_type', models.CharField(choices=[('cutting', 'Cutting'), ('sewing', 'Sewing'), ('washing', 'Washing'), ('finishing', 'Finishing')], max_length=50)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_lines', to='production.floor')),
            ],
        ),
    ]
