# Generated by Django 5.1.3 on 2025-01-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_rename_productionline_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
