# Generated by Django 5.1.3 on 2025-01-14 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_delete_location'),
        ('production', '0003_alter_line_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
