# Generated by Django 5.1.3 on 2025-02-04 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='purchase_price',
        ),
    ]
