# Generated by Django 5.1.3 on 2025-02-05 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_purchaseitem_purchase_price'),
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partsusagerecord',
            name='mechanic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mechanic_machine_part', to='user_management.employee'),
        ),
    ]
