# Generated by Django 5.1.3 on 2025-01-13 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_machine_last_problem_machine_last_repairing_start_and_more'),
        ('production', '0003_alter_line_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.line'),
        ),
        migrations.AddField(
            model_name='machine',
            name='sequence',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
