# Generated by Django 5.1.3 on 2025-01-14 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0004_machine_line_machine_sequence"),
        ("production", "0003_alter_line_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="breakdownlog",
            name="location",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="location",
        ),
        migrations.AddField(
            model_name="breakdownlog",
            name="line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="production.line",
            ),
        ),
    ]
