# Generated by Django 5.1.3 on 2025-01-14 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_delete_location'),
        ('maintenance', '0005_remove_breakdownlog_location_remove_machine_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
    ]
