# Generated by Django 5.1.3 on 2025-01-14 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        ("user_management", "0002_remove_employee_location"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
    ]
